### ISSUE TITLE
It is very slow when runing on the custom data.

### ISSUE THREAD

**Issue by Woolseyyy** [Xiaoming-Zhao/advtex_init_align#7]
I have been successed to run the repo on my custom data by transforming the data to rawstearm. However, I found it takes more than 10 hours to run. My model has 152,301 vertices and 204,012 faces and there are 70 cameras. It seems that it taks long time in "overlapping checking", "TexInit".  
Do you have any suggestion? I store all vertices in "Vertices.0" and all faces in "Faces.0". Is this the reason?

**Comment by Xiaoming-Zhao** [comment]
Hi Haoqian, these lines may be helpful:
https://github.com/Xiaoming-Zhao/advtex_init_align/blob/2f30b94090d4f04ea740b4c21a19dfb2e73328cb/run_scannet.sh#L106-L117

Essentially, this command splits the whole mesh into some sub-meshes such that the overlapping checking can be done quickly. The reason is that overlapping checking involves Markov Random Fields (MRF), which considers pairwise information between adjacent faces. This will be very slow to optimize for a large graph, namely the mesh in this case. Therefore, we split the mesh with `CGAL::METIS::partition_graph` such that the MRF only needs to be run on some small graphs.

**Comment by Woolseyyy** [comment]
Thank you!!
